# Generated by Django 5.2 on 2025-05-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(blank=True, choices=[('natural', 'Natural'), ('juridica', 'Jurídica')], max_length=10, null=True)),
                ('documento_tipo', models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('nit', 'NIT')], max_length=20, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('digito_verificacion', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('persona_diligenciadora', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.persona')),
            ],
        ),
    ]
